AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This CloudFormation template configures SageMaker Studio with minimal VPC requirements and public internet access for non-EFS traffic.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  SageMakerExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  OpenSearchDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      DomainName: !Sub "chatbot-${AWS::StackName}"
      EngineVersion: "OpenSearch_2.11"
      ClusterConfig:
        InstanceType: "r6g.large.search"
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: "gp3"
        VolumeSize: 100
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: "raguser"
          MasterUserPassword: "MarsEarth1!"
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: "Policy-Min-TLS-1-2-2019-07"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "es:*"
            Resource: "*"

  OpenSearchDomainEndpointParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "chatbot-opensearch_domain_endpoint1"
      Type: "String"
      Value: !GetAtt OpenSearchDomain.DomainEndpoint

  OpenSearchUserIDParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "chatbot-opensearch_user_id1"
      Type: "String"
      Value: "raguser"

  OpenSearchUserPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "chatbot-opensearch_user_password1"
      Type: "String"
      Value: "MarsEarth1!"

  StudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: 'WorkshopDomain'
      AuthMode: IAM
      VpcId: !Ref VPC
      SubnetIds: 
        - !Ref PublicSubnet
      AppNetworkAccessType: PublicInternetOnly
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn

  StudioUserProfile:
    Type: AWS::SageMaker::UserProfile
    DependsOn: 
      - StudioDomain
    Properties:
      DomainId: !Ref StudioDomain
      UserProfileName: WorkshopUser
      UserSettings: 
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn

Outputs:
  SageMakerConsoleLink:
    Description: SageMaker Studio console link
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/studio/
  
  SageMakerExecutionRoleArn:
    Description: SageMaker Execution Role ARN
    Value: !GetAtt SageMakerExecutionRole.Arn

  DomainEndpoint:
    Description: "Endpoint for the OpenSearch domain."
    Value: !Sub "https://${OpenSearchDomain.DomainEndpoint}"

  DashboardURL:
    Description: "URL to access the OpenSearch Dashboards."
    Value: !Sub "https://${OpenSearchDomain.DomainEndpoint}:443/app/opensearch_dashboards"

  UserID:
    Description: "User ID for OpenSearch domain."
    Value: "raguser"

  UserPassword:
    Description: "Password for OpenSearch domain."
    Value: "MarsEarth1!"
